// Build = static validation + version stamp + service-worker generation.
// The app ships as plain ES modules (no bundler), so "build" means: prove the
// sources are consistent, then stamp a content hash so caches bust correctly.
import { createHash } from "node:crypto";
import { readFileSync, readdirSync, writeFileSync, existsSync, statSync } from "node:fs";
import { join, relative, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const VERSION = "3.0.0";
const ROOT = resolve(fileURLToPath(new URL("..", import.meta.url)));
const GENERATED = new Set(["js/version.js", "sw.js"]);

const errors = [];
const fail = (msg) => errors.push(msg);
const read = (p) => readFileSync(join(ROOT, p), "utf8");

function walk(dir) {
  return readdirSync(join(ROOT, dir)).flatMap((name) => {
    const rel = dir ? `${dir}/${name}` : name;
    return statSync(join(ROOT, rel)).isDirectory() ? walk(rel) : [rel];
  });
}

// ------------------------------------------------------------------ asset list
const assets = [
  "index.html",
  "manifest.webmanifest",
  ...walk("css"),
  ...walk("js"),
  ...walk("icons"),
].filter((p) => !p.endsWith(".DS_Store"));
if (!assets.includes("js/version.js")) assets.push("js/version.js");

// ------------------------------------------------------------------ checks
const html = read("index.html");
const js = Object.fromEntries(walk("js").filter((p) => p.endsWith(".js")).map((p) => [p, read(p)]));

// 1. Every element id used by app.js exists in index.html (exactly once).
const htmlIds = [...html.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1]);
const dupIds = htmlIds.filter((id, i) => htmlIds.indexOf(id) !== i);
dupIds.forEach((id) => fail(`Duplicate id in index.html: #${id}`));
for (const m of js["js/app.js"].matchAll(/\$\("([^"]+)"\)/g)) {
  if (!htmlIds.includes(m[1])) fail(`app.js references missing element #${m[1]}`);
}

// 2. Every <use href="#…"> icon symbol is defined.
for (const m of html.matchAll(/href="#([^"]+)"/g)) {
  if (!htmlIds.includes(m[1])) fail(`index.html uses undefined icon #${m[1]}`);
}

// 3. Every relative import resolves to a file, and every named import is exported.
for (const [file, src] of Object.entries(js)) {
  for (const m of src.matchAll(/import\s*\{([^}]+)\}\s*from\s*"(\.[^"]+)"/g)) {
    const target = relative(ROOT, resolve(ROOT, dirname(file), m[2]));
    if (!existsSync(join(ROOT, target)) && !GENERATED.has(target)) { fail(`${file}: import "${m[2]}" not found`); continue; }
    if (GENERATED.has(target) && !existsSync(join(ROOT, target))) continue;
    const tsrc = read(target);
    for (const name of m[1].split(",").map((s) => s.trim().split(/\s+as\s+/)[0]).filter(Boolean)) {
      const exported = new RegExp(`export\\s+(?:async\\s+)?(?:const|let|function|class)\\s+${name}\\b`).test(tsrc);
      if (!exported) fail(`${file}: "${name}" is not exported by ${target}`);
    }
  }
}

// 4. Local files referenced from index.html / manifest exist.
for (const m of html.matchAll(/(?:src|href)="(?!https?:|#|data:)([^"]+)"/g)) {
  if (!existsSync(join(ROOT, m[1])) && !GENERATED.has(m[1])) fail(`index.html references missing file ${m[1]}`);
}
const manifest = JSON.parse(read("manifest.webmanifest"));
for (const icon of manifest.icons) if (!existsSync(join(ROOT, icon.src))) fail(`manifest icon missing: ${icon.src}`);

// 5. No framework CDNs / inline handlers (the v2 pain points).
if (/cdn\.tailwindcss|onclick=|oninput=|onchange=/.test(html)) fail("index.html must not use Tailwind CDN or inline event handlers");

if (errors.length) {
  console.error(`✗ build checks failed (${errors.length}):\n  - ${errors.join("\n  - ")}`);
  process.exit(1);
}

// ------------------------------------------------------------------ stamp
const hash = createHash("sha256");
for (const p of assets.filter((a) => !GENERATED.has(a)).sort()) hash.update(p).update(readFileSync(join(ROOT, p)));
const digest = hash.digest("hex").slice(0, 10);

const versionPath = join(ROOT, "js/version.js");
const prev = existsSync(versionPath) ? readFileSync(versionPath, "utf8") : "";
const date = prev.includes(`hash: "${digest}"`) ? prev.match(/date: "([^"]+)"/)?.[1] : new Date().toISOString().slice(0, 10);
const versionSrc = `// Generated by scripts/build.mjs — do not edit.\nexport const BUILD = { version: "${VERSION}", hash: "${digest}", date: "${date}" };\n`;
if (prev !== versionSrc) writeFileSync(versionPath, versionSrc);

const sw = `// Generated by scripts/build.mjs — do not edit.
// Network-first for app files (always fresh when online), cache fallback offline.
const CACHE = "nightfury-${VERSION}-${digest}";
const ASSETS = ${JSON.stringify(["./", ...assets.map((a) => `./${a}`)], null, 2)};

self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith("nightfury-") && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  const isFont = url.hostname.endsWith("fonts.googleapis.com") || url.hostname.endsWith("fonts.gstatic.com");
  if (url.origin !== location.origin && !isFont) return;
  e.respondWith(
    fetch(req)
      .then((res) => {
        if (res.ok || res.type === "opaque") {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy));
        }
        return res;
      })
      .catch(() => caches.match(req, { ignoreSearch: true }).then((hit) => hit || (req.mode === "navigate" ? caches.match("./index.html") : Response.error()))),
  );
});
`;
const swPath = join(ROOT, "sw.js");
if (!existsSync(swPath) || readFileSync(swPath, "utf8") !== sw) writeFileSync(swPath, sw);

console.log(`✓ build ok · v${VERSION} · ${digest} · ${assets.length} assets · ${Object.keys(js).length} modules checked`);
