// Generated by scripts/build.mjs — do not edit.
// Network-first for app files (always fresh when online), cache fallback offline.
const CACHE = "nightfury-3.0.0-e5726b5dab";
const ASSETS = [
  "./",
  "./index.html",
  "./manifest.webmanifest",
  "./css/app.css",
  "./js/app.js",
  "./js/bitmap.js",
  "./js/ble.js",
  "./js/device.js",
  "./js/font5x7.js",
  "./js/graphics.js",
  "./js/hud.js",
  "./js/presets.js",
  "./js/preview.js",
  "./js/protocol.js",
  "./js/queue.js",
  "./js/scene.js",
  "./js/sensors.js",
  "./js/store.js",
  "./js/telemetry.js",
  "./js/textraster.js",
  "./js/version.js",
  "./icons/icon-180.png",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/icon.svg"
];

self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith("nightfury-") && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  const isFont = url.hostname.endsWith("fonts.googleapis.com") || url.hostname.endsWith("fonts.gstatic.com");
  if (url.origin !== location.origin && !isFont) return;
  e.respondWith(
    fetch(req)
      .then((res) => {
        if (res.ok || res.type === "opaque") {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy));
        }
        return res;
      })
      .catch(() => caches.match(req, { ignoreSearch: true }).then((hit) => hit || (req.mode === "navigate" ? caches.match("./index.html") : Response.error()))),
  );
});
